action:Thu Jan 12 00:54:33 CST 2023

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -63,7 +63,7 @@ host_release="$(cat /etc/os-release | grep '^VERSION_CODENAME=.*' | cut -d'=' -f
 os_release_file="etc/os-release"
 # Set banner's ${BOARD_NAME}: such as [ s905x3 ]
 armbian_release_file="etc/armbian-release"
-# Add custom armbian firmware information
+# Add custom armbian information
 ophub_release_file="etc/ophub-release"
 
 # Firmware files download repository
@@ -73,13 +73,15 @@ firmware_repo="${firmware_repo//tree\/main/trunk}"
 
 # Kernel files download repository
 kernel_repo="https://github.com/ophub/kernel/tree/main/pub"
-# Common kernel directory, RK3588 kernel directory, [ rk3588 ] is the fixed name
+# Set stable kernel directory: [ stable ], rk35xx kernel directory: [ rk3588 ]
 kernel_dir=("stable" "rk3588")
-common_kernel=("6.0.10" "5.15.50")
-rk3588_kernel=("5.10.150")
+# Set the list of kernels used by default
+stable_kernel=("6.0.10" "5.15.50")
+rk35xx_kernel=("5.10.150")
+# Set to automatically use the latest kernel
 auto_kernel="true"
 
-# Set supported board
+# Set the list of supported armbian board
 build_armbian=(
     "a311d"
     "s922x" "s922x-n2" "s922x-reva"
@@ -95,13 +97,17 @@ build_armbian=(
     "r66s" "r68s"
     "beikeyun" "l1pro"
 )
+# Set the list of devices that must use the rk35xx kernel
+must_kernel_rk35xx=("rock5b")
+# Set the list of devices that must use the stable/6.x.y kernel
+must_kernel_6xy=("r66s" "r68s")
 
-# Set Armbian firmware size (Unit: MiB, BOOT_MB >= 256, ROOT_MB >= 2048)
+# Set Armbian size (Unit: MiB, BOOT_MB >= 256, ROOT_MB >= 2048)
 BOOT_MB="256"
 ROOT_MB="2560"
 # Set ROOTFS partition file system type, options: [ ext4 / btrfs ]
 ROOTFS_TYPE="ext4"
-# Custom name in firmware name: ${build_image_file}, such as _server, _dev, etc.
+# Custom name in Armbian file: ${build_image_file}, such as _server, _dev, etc.
 custom_name="_server"
 
 # Get gh_token for api.github.com
@@ -110,9 +116,9 @@ gh_token=""
 # Set font color
 STEPS="[\033[95m STEPS \033[0m]"
 INFO="[\033[94m INFO \033[0m]"
-SUCCESS="[\033[92m SUCCESS \033[0m]"
-PROMPT="[\033[93m PROMPT \033[0m]"
+TIPS="[\033[93m TIPS \033[0m]"
 WARNING="[\033[93m WARNING \033[0m]"
+SUCCESS="[\033[92m SUCCESS \033[0m]"
 ERROR="[\033[91m ERROR \033[0m]"
 #
 #========================================================================================
@@ -159,7 +165,7 @@ init_var() {
             if [[ -n "${2}" ]]; then
                 oldIFS=${IFS}
                 IFS=_
-                common_kernel=(${2})
+                stable_kernel=(${2})
                 IFS=${oldIFS}
                 shift
             else
@@ -259,7 +265,7 @@ download_depends() {
     cd ${make_path}
     echo -e "${STEPS} Start downloading dependency files..."
 
-    # Download armbian firmware files
+    # Download Armbian firmware files
     svn co ${firmware_repo} ${firmware_path} --force
 }
 
@@ -277,9 +283,9 @@ query_version() {
         {
             # Select the corresponding kernel directory and list
             if [[ "${k}" == "rk3588" ]]; then
-                down_kernel_list="${rk3588_kernel[*]}"
+                down_kernel_list="${rk35xx_kernel[*]}"
             else
-                down_kernel_list="${common_kernel[*]}"
+                down_kernel_list="${stable_kernel[*]}"
             fi
 
             # Query the name of the latest kernel version
@@ -313,19 +319,19 @@ query_version() {
 
             # Reset the kernel array to the latest kernel version
             if [[ "${k}" == "rk3588" ]]; then
-                unset rk3588_kernel
-                rk3588_kernel="${tmp_arr_kernels[*]}"
+                unset rk35xx_kernel
+                rk35xx_kernel="${tmp_arr_kernels[*]}"
             else
-                unset common_kernel
-                common_kernel="${tmp_arr_kernels[*]}"
+                unset stable_kernel
+                stable_kernel="${tmp_arr_kernels[*]}"
             fi
 
             let x++
         }
     done
 
-    echo -e "${INFO} The latest version of the common_kernel: [ ${common_kernel[*]} ]"
-    echo -e "${INFO} The latest version of the rk3588_kernel: [ ${rk3588_kernel[*]} ]"
+    echo -e "${INFO} The latest version of the stable_kernel: [ ${stable_kernel[*]} ]"
+    echo -e "${INFO} The latest version of the rk35xx_kernel: [ ${rk35xx_kernel[*]} ]"
 }
 
 download_kernel() {
@@ -337,9 +343,9 @@ download_kernel() {
         {
             # Set the kernel download list
             if [[ "${k}" == "rk3588" ]]; then
-                down_kernel_list="${rk3588_kernel[*]}"
+                down_kernel_list="${rk35xx_kernel[*]}"
             else
-                down_kernel_list="${common_kernel[*]}"
+                down_kernel_list="${stable_kernel[*]}"
             fi
 
             # Download the kernel to the storage directory
@@ -549,11 +555,10 @@ copy_files() {
     # Mount rootfs
     if [[ "${ROOTFS_TYPE}" == "btrfs" ]]; then
         mount -t btrfs -o discard,compress=zstd:6 ${loop_new}p2 ${tag_rootfs}
-        [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p2 failed!"
     else
         mount -t ext4 -o discard ${loop_new}p2 ${tag_rootfs}
-        [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p2 failed!"
     fi
+    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p2 failed!"
 
     # Copy the full Armbian image
     cp -af ${tmp_armbian}/* ${tag_rootfs}
@@ -659,6 +664,13 @@ refactor_files() {
     rm -rf usr/lib/linux-image-*
     rm -f usr/sbin/ddbr
     rm -f var/lib/dpkg/info/linux-image*
+    # Remove motd-news related services
+    rm -f usr/lib/systemd/system/motd-news.timer
+    rm -f usr/lib/systemd/system/motd-news.service
+    rm -f var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/motd-news.timer
+    rm -f var/lib/systemd/deb-systemd-helper-enabled/motd-news.timer.dsh-also
+    rm -f etc/systemd/system/timers.target.wants/motd-news.timer
+    rm -f etc/update-motd.d/50-motd-news
 
     # Rebuild symbolic link files (ln -sf ${target} ${symbolic_link_file})
     ln -sf /usr/bin bin
@@ -687,7 +699,7 @@ refactor_files() {
     [[ -f "usr/libexec/sudo/sudoers.so" ]] && chmod 644 usr/libexec/sudo/sudoers.so
     [[ -f "usr/libexec/polkit-agent-helper-1" ]] && chmod 4755 usr/libexec/polkit-agent-helper-1
 
-    # Add custom firmware information
+    # Add custom Armbian information
     echo "PLATFORM='${PLATFORM}'" >>${ophub_release_file}
     echo "VERSION_CODEID='${release_codeid}'" >>${ophub_release_file}
     echo "VERSION_CODENAME='${release_codename}'" >>${ophub_release_file}
@@ -736,14 +748,6 @@ refactor_files() {
     [[ -f "${motd_tips}" ]] && sed -i 's|^MOTD_DISABLE=.*|MOTD_DISABLE="tips"|g' ${motd_tips}
     quotes_cron="etc/cron.weekly/armbian-quotes"
     [[ -f "${quotes_cron}" ]] && sed -i "s|^curl |#curl |g" ${quotes_cron}
-
-    # Remove motd-news related services
-    rm -f usr/lib/systemd/system/motd-news.timer
-    rm -f usr/lib/systemd/system/motd-news.service
-    rm -f var/lib/systemd/deb-systemd-helper-enabled/timers.target.wants/motd-news.timer
-    rm -f var/lib/systemd/deb-systemd-helper-enabled/motd-news.timer.dsh-also
-    rm -f etc/systemd/system/timers.target.wants/motd-news.timer
-    rm -f etc/update-motd.d/50-motd-news
 
     # Make the .bashrc take effect, Default shell settings file: /etc/default/useradd
     echo '[[ "${SHELL}" == *bash && -f "${HOME}/.bashrc" ]] && . ${HOME}/.bashrc' >>etc/profile
@@ -847,7 +851,7 @@ clean_tmp() {
 
 loop_rebuild() {
     cd ${make_path}
-    echo -e "${STEPS} Start building Armbian firmware..."
+    echo -e "${STEPS} Start building Armbian..."
 
     j="1"
     for b in ${build_armbian[*]}; do
@@ -856,27 +860,27 @@ loop_rebuild() {
             confirm_version
 
             # Determine kernel branch
-            if [[ "${KERNEL_BRANCH}" == "rk3588" ]]; then
-                build_kernel="${rk3588_kernel[*]}"
+            if [[ -n "$(echo "${must_kernel_rk35xx[@]}" | grep -w "${board}")" ]]; then
+                kernel_list="${rk35xx_kernel[*]}"
                 kd="rk3588"
             else
-                build_kernel="${common_kernel[*]}"
+                kernel_list="${stable_kernel[*]}"
                 kd="$(echo "${kernel_dir[@]}" | sed -e "s|rk3588||" | xargs)"
             fi
 
             i="1"
-            for k in ${build_kernel[*]}; do
+            for k in ${kernel_list[*]}; do
                 {
                     kernel="${k}"
 
-                    # Rockchip rk3568 series, such as FastRhino R66S/R68S only support 6.0.y and above kernel
-                    [[ "${SOC,,}" == "rk3568" && "${kernel:0:1}" -ne "6" ]] && {
-                        echo -e "(${j}.${i}) ${PROMPT} ${board}(${SOC,,}) cannot use ${kernel} kernel, skip."
+                    # Identify devices that must use the 6.x.y kernel
+                    [[ -n "$(echo "${must_kernel_6xy[@]}" | grep -w "${board}")" && "${kernel:0:1}" -ne "6" ]] && {
+                        echo -e "(${j}.${i}) ${TIPS} The ${board} device cannot use ${kd}/${kernel} kernel, skip."
                         let i++
                         continue
                     }
 
-                    echo -ne "(${j}.${i}) Start building Armbian [ ${b} - ${kd}/${k} ]. "
+                    echo -ne "(${j}.${i}) Start building Armbian [ ${board} - ${kd}/${kernel} ]. "
                     now_remaining_space="$(df -Tk ${make_path} | grep '/dev/' | awk '{print $5}' | echo $(($(xargs) / 1024 / 1024)))"
                     if [[ "${now_remaining_space}" -le "6" ]]; then
                         echo -e "${WARNING} Remaining space is less than 6G, exit this build."
@@ -927,12 +931,12 @@ download_depends
 [[ "${auto_kernel}" == "true" ]] && query_version
 download_kernel
 #
-echo -e "${INFO} Armbian Board List: [ $(echo ${build_armbian[*]} | tr "\n" " ") ]"
-echo -e "${INFO} COMMON Kernel List: [ $(echo ${common_kernel[*]} | tr "\n" " ") ]"
-echo -e "${INFO} RK3588 Kernel List: [ $(echo ${rk3588_kernel[*]} | tr "\n" " ") ]"
-echo -e "${INFO} ROOTFS Type: [ ${ROOTFS_TYPE} ] \n"
+echo -e "${INFO} Armbian board list: [ $(echo ${build_armbian[*]} | tr "\n" " ") ]"
+echo -e "${INFO} Stable kernel list: [ $(echo ${stable_kernel[*]} | tr "\n" " ") ]"
+echo -e "${INFO} Rk35xx Kernel list: [ $(echo ${rk35xx_kernel[*]} | tr "\n" " ") ]"
+echo -e "${INFO} ROOTFS type: [ ${ROOTFS_TYPE} ] \n"
 #
-# Loop to rebuild armbian firmware
+# Loop to rebuild armbian
 loop_rebuild
 #
 # Show server end information
