action:Thu Apr 13 00:38:27 CST 2023

diff --git a/rebuild b/rebuild
--- a/rebuild
+++ b/rebuild
@@ -21,9 +21,11 @@
 #
 # error_msg          : Output error message
 # process_msg        : Output process message
+# mount_again        : Mount the image file, fail again
 # get_textoffset     : Get kernel TEXT_OFFSET
 #
 # init_var           : Initialize all variables
+# check_data         : Check the validity of the data
 # find_armbian       : Find Armbian file (build/output/images/*.img)
 # download_depends   : Download the dependency files
 # query_version      : Query the latest kernel version
@@ -117,6 +119,37 @@ error_msg() {
 
 process_msg() {
     echo -e " [\033[1;92m ${board} - ${kernel} \033[0m] ${1}"
+}
+
+mount_again() {
+    # Check mount parameters
+    m_type="${1}"
+    m_dev="${2}"
+    m_target="${3}"
+    [[ -n "${m_type}" && -n "${m_dev}" && -n "${m_target}" ]] || {
+        error_msg "Mount parameter is missing: [ ${m_type}, ${m_dev}, ${m_target} ]"
+    }
+
+    i="1"
+    max_try="10"
+    while [[ "${i}" -le "${max_try}" ]]; do
+        # Mount according to the image partition format
+        if [[ "${m_type}" == "btrfs" ]]; then
+            mount -t ${m_type} -o discard,compress=zstd:6 ${m_dev} ${m_target}
+        else
+            mount -t ${m_type} -o discard ${m_dev} ${m_target}
+        fi
+
+        # Mount failed and continue trying
+        if [[ "${?}" -eq "0" ]]; then
+            break
+        else
+            sync && sleep 3
+            umount -f ${m_target} 2>/dev/null
+            i="$((i + 1))"
+        fi
+    done
+    [[ "${i}" -gt "${max_try}" ]] && error_msg "[ ${i} ] attempts to mount failed."
 }
 
 get_textoffset() {
@@ -215,7 +248,9 @@ init_var() {
         esac
         shift
     done
+}
 
+check_data() {
     # Columns of ${model_conf}:
     # 1.ID  2.MODEL  3.SOC  4.FDTFILE  5.UBOOT_OVERLOAD  6.MAINLINE_UBOOT  7.BOOTLOADER_IMG  8.DESCRIPTION
     # 9.KERNEL_TAGS  10.PLATFORM  11.FAMILY  12.BOOT_CONF  13.BOARD  14.BUILD
@@ -483,8 +518,7 @@ extract_armbian() {
     loop_old="$(losetup -P -f --show "${armbian_image_file}")"
     [[ -n "${loop_old}" ]] || error_msg "losetup ${armbian_image_file} failed."
 
-    mount -o discard ${loop_old}p1 ${tmp_armbian}
-    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_old}p1 failed!"
+    mount_again ext4 ${loop_old}p1 ${tmp_armbian}
 
     cd ${tmp_armbian}
 
@@ -623,19 +657,17 @@ copy_files() {
 
     # Mount bootfs
     if [[ "${bootfs_type}" == "fat32" ]]; then
-        mount -t vfat -o discard ${loop_new}p1 ${tag_bootfs}
+        mount_again vfat ${loop_new}p1 ${tag_bootfs}
     else
-        mount -t ext4 -o discard ${loop_new}p1 ${tag_bootfs}
+        mount_again ext4 ${loop_new}p1 ${tag_bootfs}
     fi
-    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p1 failed!"
 
     # Mount rootfs
     if [[ "${rootfs_type}" == "btrfs" ]]; then
-        mount -t btrfs -o discard,compress=zstd:6 ${loop_new}p2 ${tag_rootfs}
+        mount_again btrfs ${loop_new}p2 ${tag_rootfs}
     else
-        mount -t ext4 -o discard ${loop_new}p2 ${tag_rootfs}
+        mount_again ext4 ${loop_new}p2 ${tag_rootfs}
     fi
-    [[ "${?}" -eq "0" ]] || error_msg "mount ${loop_new}p2 failed!"
 
     # Copy the full Armbian image
     cp -af ${tmp_armbian}/* ${tag_rootfs}
@@ -1067,6 +1099,7 @@ echo -e "${INFO} Server running on Ubuntu: [ Release: ${host_release} / Host: ${
 
 # Initialize variables
 init_var "${@}"
+check_data
 # Find rebuild files
 find_armbian
 # Download the dependency files
